"""Compute source-PPO state values, normalized with training-corpus moments.

The input must be the relabeled corpus generated by the 40-checkpoint,
17-row, eight 50-step-block MiniGrid collector, with checkpoint-return J
stored in rewards. Checkpoint identity is checked against those J labels.
"""
import argparse
import json
import pickle
import re
from pathlib import Path

import numpy as np
from minigrid_ppo_targets import derive_selected_eval_indices, derive_row_block_mapping, SB3ValueBackend
from train_cv_minigrid import sha256


def normalize_ppo_values(values, current_j):
    values = np.asarray(values, dtype=np.float64)
    current_j = np.asarray(current_j, dtype=np.float64)
    if values.shape != current_j.shape or not np.isfinite(values).all() or not np.isfinite(current_j).all():
        raise ValueError('Targets must be finite and aligned.')
    mv, sv, mj, sj = values.mean(), values.std(ddof=0), current_j.mean(), current_j.std(ddof=0)
    if min(sv, sj) <= 0: raise ValueError('Both training target variances must be positive.')
    return (mj + sj * (values - mv) / sv).astype(np.float32)


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--train-data', required=True)
    p.add_argument('--val-data', required=True)
    p.add_argument('--eval-results', required=True, help='Evaluated PPO returns separated by commas or newlines, sorted by checkpoint steps.')
    p.add_argument('--checkpoint-dir', required=True, help='Contains ppo_<steps>_steps.zip files.')
    p.add_argument('--output-dir', required=True)
    p.add_argument('--device', default='cpu')
    p.add_argument('--batch-size', type=int, default=8192)
    return p.parse_args(argv)


def build(a, backend=None):
    if a.batch_size < 1: raise ValueError('Batch size must be positive.')
    out = Path(a.output_dir); out.mkdir(parents=True, exist_ok=False)
    checkpoint_files = {}
    for path in Path(a.checkpoint_dir).glob('ppo_*_steps.zip'):
        match = re.fullmatch(r'ppo_(\d+)_steps.zip', path.name)
        if match: checkpoint_files[int(match[1])] = path
    versions = sorted(checkpoint_files)
    scores = np.asarray([float(token) for token in re.split(r'[\s,]+', Path(a.eval_results).read_text().strip()) if token])
    if len(versions) != len(scores): raise ValueError('Checkpoint count and evaluated returns differ.')
    mapping = derive_row_block_mapping(derive_selected_eval_indices(scores))
    steps = np.empty((17, 400), dtype=np.int64)
    expected_j = np.empty((17, 400), dtype=np.float64)
    for row in mapping:
        for block, idx in enumerate(row['eval_indices']):
            sl = slice(block * 50, (block + 1) * 50)
            steps[row['row_pattern'], sl] = versions[idx]
            expected_j[row['row_pattern'], sl] = scores[idx]
    backend = backend or SB3ValueBackend(a.device)
    identities = {str(int(v)): {'file': checkpoint_files[int(v)].name,
                               'sha256': sha256(checkpoint_files[int(v)])} for v in np.unique(steps)}
    splits = {}
    moments = None
    for split, dataset_path in [('train', a.train_data), ('val', a.val_data)]:
        with open(dataset_path, 'rb') as f: data = pickle.load(f)
        states = data['observations']; labels = np.asarray(data['rewards'])
        if labels.ndim == 3 and labels.shape[-1] == 1: labels = labels[..., 0]
        if states.shape[1:] != (400, 3, 7, 7) or states.shape[0] % 17 or labels.shape != states.shape[:2]:
            raise ValueError('Expected aligned [17*n,400,3,7,7] observations and [17*n,400] labels.')
        if split == 'train':
            for start in range(0, len(labels), 17):
                if not np.allclose(labels[start:start + 17], expected_j, rtol=1e-7, atol=1e-7):
                    raise ValueError('Checkpoint-return labels do not verify the reconstructed row mapping.')
        raw = np.lib.format.open_memmap(out / f'{split}_raw_ppo_values.npy', mode='w+', dtype=np.float32, shape=labels.shape)
        for version in np.unique(steps):
            model = backend.load(checkpoint_files[int(version)])
            row_pattern, time = np.nonzero(steps == version)
            for offset in range(0, len(labels), 17):
                for start in range(0, len(time), a.batch_size):
                    rows = row_pattern[start:start + a.batch_size] + offset
                    times = time[start:start + a.batch_size]
                    raw[rows, times] = backend.predict_values(model, states[rows, times])
            backend.release(model)
        raw.flush()
        if split == 'train':
            mv, sv = float(raw.mean(dtype=np.float64)), float(raw.std(dtype=np.float64))
            mj, sj = float(labels.mean(dtype=np.float64)), float(labels.std(dtype=np.float64))
            if min(sv, sj) <= 0 or not np.isfinite([mv, sv, mj, sj]).all(): raise ValueError('Invalid target moments.')
            moments = {'mu_V': mv, 'sigma_V': sv, 'mu_J': mj, 'sigma_J': sj}
        target_path = out / f'{split}_ppo_state.npy'
        target = np.lib.format.open_memmap(target_path, mode='w+', dtype=np.float32, shape=labels.shape)
        for start in range(0, len(labels), 256):
            target[start:start + 256] = mj + sj * (raw[start:start + 256].astype(np.float64) - mv) / sv
        target.flush()
        splits[split] = {'data_sha256': sha256(dataset_path), 'target_sha256': sha256(target_path)}
        del data, states, raw, target
    manifest = {'splits': splits, 'eval_results_sha256': sha256(a.eval_results),
                'checkpoints': identities, 'row_mapping': mapping,
                'training_moments': moments,
                'formula': 'mu_J + sigma_J * (V_PPO(s) - mu_V) / sigma_V'}
    (out / 'manifest.json').write_text(json.dumps(manifest, indent=2, allow_nan=False))


def main(argv=None):
    build(parse_args(argv))


if __name__ == '__main__': main()
